### PR TITLE
Update gitignore to ignore tox and pyenv local version

### PR DESCRIPTION
**Pull request by nsorros**
Description
---

Checklist
---

- [ ] Added link to Github issue or Trello card
- [ ] Added tests

### CODE REVIEW

**Review by lizgzil — APPROVED** [review]
👍

**Comment by aCampello** [comment]
I'm happy to see the warnings...

**Comment by nsorros** [comment]
> I'm happy to see the warnings...

I think this replies on a different PR #252  :P but noted

**Comment by aCampello** [comment]
Lol - so many PR's opened :D

**Pull request merged**
