### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by aCampello**
Description
---
Release 1.1.0

Checklist
---
- [x] Change `wellcomeml/__version__.py`
- [x] Add changelog
- [x] `make dist`
- [x] Verify new package was generated correctly on the [pip registry](https://pypi.org/project/wellcomeml)
 and GitHub releases

### CODE REVIEW

**Comment by aCampello** [comment]
Will run `make dist` when approved.

**Comment by aCampello** [comment]
[Release new version WellcomeML](https://trello.com/c/qNh3YXCG/1235-release-new-version-wellcomeml)

**Review by lizgzil — APPROVED** [review]
👍

**Comment by aCampello** [comment]
Starting to release...

**Comment by aCampello** [comment]
Uploaded correctly. We're on 1.1.0 on pipit

**Comment by aCampello** [comment]
And on GitHub. 🎉

**Pull request merged**
