### PR TITLE
Update examples doc

### PR DESCRIPTION
**Pull request by lizgzil**
Description
---
adding examples for train spacy NER and similarity entity linking.

Checklist
---

Addressing some of https://github.com/wellcometrust/WellcomeML/issues/79

### CODE REVIEW

**Comment by aCampello** [comment]
You might have to re-generate the docs, as per in the README.md (2.2) - ignore me if you have done this already:

### 2.2 Contributing to the docs

Make changes to the .rst files in `/docs` (please **do not change the ones starting by wellcomeml** as those are generated automatically)

Navigate to the root repository and run

```bash
make update-docs
```

**Comment by lizgzil** [comment]
@aCampello `make update-docs` did more than I expected! does it look correct? (I personally only made changes to examples.rst)

**Comment by aCampello** [comment]
Yes, it picks up the new classes/methods we developed as well. 

Then you can just verify that `_build/html/index.html` has generated correctly and looks OK.

**Review by aCampello — APPROVED** [review]
Looks good to me.

**Pull request merged**
