### PR TITLE
Fix version to latest version on PyPi

### LINKED ISSUE #206: Incosistent version number in master and PyPi
Our latest release `2021.02.0` did not update the internal version which might create problem as pip might complain in the future if someone asks for a specific version in which it will use the version file to check. We need to update to `2020.02.1` asap to fix this as we cannot overwrite `2020.02.0`

### PR DESCRIPTION
**Pull request by nsorros**
Description
---

We forgot to update the version internal during the last release. Unfortunately we cannot overwrite the version in PyPi so this just fixes the problem for those cloning and using from Github. Ideally we want to update to `2021.02.1` and upload to PyPi which I am happy to do.

Fixes #206
 
Checklist
---

- [x] Added link to Github issue or Trello card
- [ ] Added tests

### CODE REVIEW

**Review by lizgzil — APPROVED** [review]
good spot

**Comment by nsorros** [comment]
Should we merge this or increase to `2020.02.1` and release? @aCampello @lizgzil I think the second is possibly better

**Review by aCampello — APPROVED** [review]
Go for it

**Comment by aCampello** [comment]
I think we need to do both - merge and update.

**Comment by nsorros** [comment]
Released https://pypi.org/project/wellcomeml/2021.2.1/

**Pull request merged**
