### PR TITLE
Update version to 2020.07.0

### LINKED ISSUE #99: Create release 2020.07.0
Models
---
* Adds Doc2VecVectorizer
* Adds WellcomeVotingClassifier
* Adds Sent2VecVectorizer
* Adds SemanticEquivalenceMetaClassifier
* Adds CategoricalMetrics and MetricMiniBatchHistory

Datasets
---
* Adds CONLL dataset
* Adds Winer dataset

Features
---
* Automatically load models like en_core_web_sm and en_trf_bertbaseuncased_lg but also download packages like sent2vec, only when needed
* Adds docs based on sphinx and read the docs

Repo
---
* Adds pep8 / flake8 checks and address violations
* Adds badges for build, codecov and license
* Adds pull request template that forces link to issue or trello

Bugs
---
* Fix dependency on non pypi packages for tests
* Pin spacy transformers to 0.5.1 
* Fix codecov running in separate travis venv

### PR DESCRIPTION
**Pull request by nsorros**
Description
---

Fixes #99 

Checklist
---

- [x] Added link to Github issue or Trello card
- [ ] Added tests

### CODE REVIEW

**Comment by nsorros** [comment]
Have a look at the issue #99 and let me know if I am omitting anything. I will then copy and paste to the changelog and in the release.

**Comment by nsorros** [comment]
> Do you also need to update the CHANGELOG.md in this PR? (could just write what you wrote in the issue description #99)

Thats the plan

**Comment by nsorros** [comment]
We are live https://pypi.org/project/wellcomeml/. For some reason this does not have an approval yet but the new version is up both in pypi, github and aws @lizgzil @aCampello

**Comment by aCampello** [comment]
How does it fix https://github.com/wellcometrust/WellcomeML/issues/101

**Comment by nsorros** [comment]
> How does it fix #101

Forgot to push the commit for that. Doing that now.

**Comment by aCampello** [comment]
> > How does it fix #101
> 
> Forgot to push the commit for that. Doing that now.

I think I would have a preference to add to the Makefile (https://github.com/wellcometrust/WellcomeML/issues/101), but if you want to merge we can do that in a subsequent PR

**Comment by nsorros** [comment]
> > > How does it fix #101
> > 
> > 
> > Forgot to push the commit for that. Doing that now.
> 
> I think I would have a preference to add to the Makefile (#101), but if you want to merge we can do that in a subsequent PR

I would agree that it makes more sense as the docs requirement is only needed for docs and not for the entire library. I am not 100% sure whether the requirements should live in the docs folder but this is a separate discusssion. Will do the change here.

**Pull request merged**
