### PR TITLE
Improve memory efficiency of TransformersTokenizer by buffering encodings

### LINKED ISSUE #253: TransformersTokenizer uses too much memory for encoding and tokenizing
TransformersTokenizer currently leverages transformers `.encode_batch` which returns `Encodings`
object which holds not only the integers associated but also the tokens and other information
which uses too much memory. Sending 1M texts from it to transform consumes more than the 60GB
of the p2.xlarge instance.

### PR DESCRIPTION
**Pull request by nsorros**
Description
---

Fixes #253

Did not add tests as the code runs as part of the tests
and the addition is an internal function to the class

Checklist
---

- [x] Added link to Github issue or Trello card
- [ ] Added tests

### CODE REVIEW

**Comment by nsorros** [comment]
[Train CNN with TransformerTokenizer that will result in smaller vocabulary and thus smaller model](https://trello.com/c/ixcKfgnI/1167-train-cnn-with-transformertokenizer-that-will-result-in-smaller-vocabulary-and-thus-smaller-model)

**Comment by nsorros** [comment]
> # [Codecov](https://codecov.io/gh/wellcometrust/WellcomeML/pull/255?src=pr&el=h1) Report
> > Merging [#255](https://codecov.io/gh/wellcometrust/WellcomeML/pull/255?src=pr&el=desc) ([002027d](https://github.com/wellcometrust/WellcomeML/commit/002027df2a8c7f088ef96883d73b075ddf33f838)) into [main](https://codecov.io/gh/wellcometrust/WellcomeML/commit/5f31fac60a6883d1ca9106f68bc48bc4e40bf227?el=desc) ([5f31fac](https://github.com/wellcometrust/WellcomeML/commit/5f31fac60a6883d1ca9106f68bc48bc4e40bf227)) will **decrease** coverage by `0.24%`.
> > The diff coverage is `61.90%`.
> 
> [Impacted file tree graph](https://codecov.io/gh/wellcometrust/WellcomeML/pull/255?src=pr&el=tree)
> 
> ```diff
> @@            Coverage Diff             @@
> ##             main     #255      +/-   ##
> ==========================================
> - Coverage   85.65%   85.40%   -0.25%     
> ==========================================
>   Files          41       41              
>   Lines        2237     2254      +17     
> ==========================================
> + Hits         1916     1925       +9     
> - Misses        321      329       +8     
> ```
> 
> [Impacted Files](https://codecov.io/gh/wellcometrust/WellcomeML/pull/255?src=pr&el=tree)	Coverage Δ	
> [wellcomeml/ml/transformers_tokenizer.py](https://codecov.io/gh/wellcometrust/WellcomeML/pull/255/diff?src=pr&el=tree#diff-d2VsbGNvbWVtbC9tbC90cmFuc2Zvcm1lcnNfdG9rZW5pemVyLnB5)	`83.75% <61.90%> (-8.32%)`	⬇️
> [Continue to review full report at Codecov](https://codecov.io/gh/wellcometrust/WellcomeML/pull/255?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/wellcometrust/WellcomeML/pull/255?src=pr&el=footer). Last update [5f31fac...002027d](https://codecov.io/gh/wellcometrust/WellcomeML/pull/255?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

at least codecov worked #251. Still not sure when it is being picked up and when not.

**Review by aCampello — APPROVED** [review]
LGTM. So you are clearing `texts_batch` every 1000 iterations so it doesn't keep in memory. Good idea!

**Comment by nsorros** [comment]
> LGTM. So you are clearing `texts_batch` every 1000 iterations so it doesn't keep in memory. Good idea!

exactly, I have written that buffering logic so many times by now, maybe I should make it a package

**Pull request merged**
