### PR TITLE
Fix pip dependency resolver

### LINKED ISSUE #195: New pip dependency resolver stalls builds
Build last lines
```
Collecting rsa<5,>=3.1.4
682  Downloading rsa-4.6-py3-none-any.whl (47 kB)
683
684  Downloading rsa-4.5-py2.py3-none-any.whl (36 kB)
685  Downloading rsa-4.4.1-py2.py3-none-any.whl (33 kB)
686  Downloading rsa-4.3-py2.py3-none-any.whl (36 kB)
687  Downloading rsa-4.2.tar.gz (46 kB)
688
689  Downloading rsa-4.1-py3-none-any.whl (32 kB)
690  Downloading rsa-4.0-py2.py3-none-any.whl (38 kB)
691  Downloading rsa-3.4.2-py2.py3-none-any.whl (46 kB)
692
693  Downloading rsa-3.4.1-py2.py3-none-any.whl (46 kB)
694
695  Downloading rsa-3.4-py2.py3-none-any.whl (46 kB)
696
697  Downloading rsa-3.3-py2.py3-none-any.whl (44 kB)
698
699  Downloading rsa-3.2.3-py2.py3-none-any.whl (44 kB)
700
701  Downloading rsa-3.2.2-py2.py3-none-any.whl (44 kB)
702
703  Downloading rsa-3.2-py2.py3-none-any.whl (43 kB)
704
705  Downloading rsa-3.1.4.tar.gz (36 kB)
706
707
708No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
709Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
710
711The build has been terminated
```

### PR DESCRIPTION
**Pull request by nsorros**
Description
---

Fixes #195 

Checklist
---

- [x] Added link to Github issue or Trello card
- [ ] Added tests

### CODE REVIEW

**Comment by aCampello** [comment]
Can we not downgrade pip in travis until `pip` sort their stuff out? It seems all issues in their repository about this are pretty much open https://github.com/pypa/pip/issues/9187

**Comment by nsorros** [comment]
> Can we not downgrade pip in travis until `pip` sort their stuff out? It seems all issues in their repository about this are pretty much open [pypa/pip#9187](https://github.com/pypa/pip/issues/9187)

We are essentially downgrading by using `--use-deprecated=legacy-resolver`

I guess the question is also whether we should pin at this point or not. I think we should move towards pinning the requirements.

**Comment by nsorros** [comment]
Closing this due to #196

**Comment by nsorros** [comment]
[Resolve WellcomeML errors in master and branches](https://trello.com/c/3GIiOwCl/1170-resolve-wellcomeml-errors-in-master-and-branches)

**Pull request closed without merging**
