### PR TITLE
Add github action to run tox

### LINKED ISSUE #247: Use Github actions instead of Travis
No major reason why Github is better than Travis but some small points why we might want to do that
* keep everything in one place
* have separate check for build in python 3.7 and 3.8 in the same way we have a different check for flake8 checks which is a GitHub action
* ability to run 20 jobs in parallel instead of 3 with travis

Some discussion on the differences https://tomasvotruba.com/blog/2020/01/27/switch-travis-to-github-actions-to-reduce-stress/

### PR DESCRIPTION
**Pull request by nsorros**
Description
---

The intention here is to transition to GitHub actions from Travis. I am not 100% sure what was the motivation, @aCampello can you provide some context?

Fixes #247 

Checklist
---

- [x] Added link to Github issue or Trello card
- [ ] Added tests

### CODE REVIEW

**Comment by nsorros** [comment]
[Migrate to GitHub actions from Travis in WellcomeML](https://trello.com/c/fEqQAovj/1245-migrate-to-github-actions-from-travis-in-wellcomeml)

**Comment by nsorros** [comment]
Adding @jdu to this PR as well. Curently the GitHub Actions are probably running into some usage limitation which is not well documented, probably around memory. @jdu though reminded me that the intention is to run the jobs in our own infrastructure using self hosted runners and code build which will eliminate this issue.

I am under the impression we do not need to do many changes to this PR to accommodate the self hosted runners, possibly only the `runs_on` bit.

**Comment by ivyleavedtoadflax** [comment]
> Adding @jdu to this PR as well. Curently the GitHub Actions are probably running into some usage limitation which is not well documented, probably around memory. @jdu though reminded me that the intention is to run the jobs in our own infrastructure using self hosted runners and code build which will eliminate this issue.
> 
> I am under the impression we do not need to do many changes to this PR to accommodate the self hosted runners, possibly only the `runs_on` bit.

Using self hosted runners is exactly what CML: https://github.com/iterative/cml

**Comment by aCampello** [comment]
This is a great PR, and I agree that Github hosting is not powerful enough to run it. 

It needs some modifications to run on our host. Checkout: https://github.com/wellcometrust/hitl/blob/main/.github/workflows/main.yaml

Also needs @jdu to create a code build project.

**Comment by nsorros** [comment]
> This is a great PR, and I agree that Github hosting is not powerful enough to run it.
> 
> It needs some modifications to run on our host. Checkout: https://github.com/wellcometrust/hitl/blob/main/.github/workflows/main.yaml
> 
> Also needs @jdu to create a code build project.

This is pending on @jdu for the containers and codebuild, then I will do something similar to hitl hopefully

**Comment by nsorros** [comment]
@jdu have we made any progress in regards to this?

**Comment by nsorros** [comment]
Closing this but happy to resume when the custom containers are setup @jdu @aCampello

**Comment by jdu** [comment]
I'll have a look at this tomorrow potentially, the runners are configured and there (we have 4 of them) we just need to configure a CodeBuild project for this repo. I've just noticed the runners are now "Offline" which they aren't so there's some disconnect there, potentially they need updating as the runnner integration interface is a bit volatile at the moment.

**Pull request closed without merging**
