### PR TITLE
Update make test to use tox

### PR DESCRIPTION
**Pull request by nsorros**
Description
---

Update `make test` command to use `tox`

Checklist
---

- [ ] Added link to Github issue or Trello card
- [ ] Added tests

### CODE REVIEW

**Comment by nsorros** [comment]
In regards to codecov #251, the report is not showing up here either. No obvious explanation to my mind as to why

**Comment by nsorros** [comment]
@aCampello @lizgzil

**Comment by lizgzil** [comment]
Seems like the tests take a lot longer. I'm also getting a lot of warnings that I don't think I've seen before in `tests/test_clustering.py`:
```
[2021-03-22 16:06:51,738] [WARNING] [W108] The rule-based lemmatizer did not find POS annotation for the token 'Crick'. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
```

**Review by lizgzil — APPROVED** [review]
This looks fine and the tests work for 3.7, but see my above comment on performance. Is there a reason this way should be slower? I think the tests have taken over 20 mins, and that is only for 3.7. I assume it's double that for checking in 3.8 too? I think it was more like 5-10 mins before.

**Comment by lizgzil** [comment]
> Seems like the tests take a lot longer. I'm also getting a lot of warnings that I don't think I've seen before in `tests/test_clustering.py`:
> 
> ```
> [2021-03-22 16:06:51,738] [WARNING] [W108] The rule-based lemmatizer did not find POS annotation for the token 'Crick'. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
> ```

ah of course, previously we disabled warnings

**Comment by nsorros** [comment]
> > Seems like the tests take a lot longer. I'm also getting a lot of warnings that I don't think I've seen before in `tests/test_clustering.py`:
> > ```
> > [2021-03-22 16:06:51,738] [WARNING] [W108] The rule-based lemmatizer did not find POS annotation for the token 'Crick'. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
> > ```
> 
> ah of course, previously we disabled warnings

how were we disabling warnings before?

**Comment by nsorros** [comment]
> > > Seems like the tests take a lot longer. I'm also getting a lot of warnings that I don't think I've seen before in `tests/test_clustering.py`:
> > > ```
> > > [2021-03-22 16:06:51,738] [WARNING] [W108] The rule-based lemmatizer did not find POS annotation for the token 'Crick'. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
> > > ```
> > 
> > 
> > ah of course, previously we disabled warnings
> 
> how were we disabling warnings before?

hey @lizgzil or @aCampello do you know the answer to this? i.e. should I do something to disable warning again?

**Comment by lizgzil** [comment]
@nsorros previously in pytest we used the `--disable-warnings` flag. I can't find whether tox has the same functionality! Regardless, I looked back to the l[ast job in Travis main](https://travis-ci.com/github/wellcometrust/WellcomeML/jobs/492733388) and it has the warnings anyway! So i guess `--disable-warnings` has never been working in the way I'd expect it to

**Comment by aCampello** [comment]
I'm happy to see the warnings...

**Pull request merged**
