### PR TITLE
Fix OOM error during CNN predict

### PR DESCRIPTION
**Pull request by nsorros**
Description
---

Fixes #297 

Tensorflow dataset is already an iterator so to yield elements we would have to do
```
from X_batch in X:
    yield X_batch
```

python `from` is equivalent to the above syntax.

Checklist
---

- [x] Added link to Github issue or Trello card
- [ ] Added tests

### CODE REVIEW

**Comment by nsorros** [comment]
[Debug Mesh training](https://trello.com/c/OzW6MNAQ/1215-debug-mesh-training)

**Review by aCampello — APPROVED** [review]
Easy PR to review! :) Wellcome back!

**Comment by aCampello** [comment]
Some non-deterministic test failed: 
`tests/test_cnn.py::test_XY_dataset_sparse_y` 

I will try to re-run again to see if it's just common randomness or something to do with the change. Will unlock the merge once it passes.

**Review by aCampello — CHANGES_REQUESTED** [review]
Just locking it for a while until the test passes ! But code LGTM.

**Comment by nsorros** [comment]
> Just locking it for a while until the test passes ! But code LGTM.

did you notice the test coverage report?

**Comment by nsorros** [comment]
I have also pushed a new commit which has not been picked up that solves the test problem

**Comment by aCampello** [comment]
> I have also pushed a new commit which has not been picked up that solves the test problem

Hmm, there seems to be only one commit in the PR. Did you push it? Seems that re-starting the pipeline didn't fix.

**Comment by aCampello** [comment]
> > Just locking it for a while until the test passes ! But code LGTM.
> 
> did you notice the test coverage report?

Yeah, the coverage report is fine. It's because the new way of splitting the tests "Bert" and "not bert" in travis, it only updates the full report if both pipelines pass.

**Review by aCampello — APPROVED** [review]
Looking good now :shipit:

**Pull request merged**
