### PR TITLE
Feature/release 2020.07.1

### PR DESCRIPTION
**Pull request by aCampello**
Description
---

Checklist
---

- [x] Added link to Github issue or Trello card
Update version https://trello.com/c/Z5zkp0Of/1043-bump-wellcomeml-version
- [ ] Added tests

### CODE REVIEW

**Comment by aCampello** [comment]
Docs updated

**Comment by aCampello** [comment]
Wheels updated

**Comment by aCampello** [comment]
Release created

**Comment by aCampello** [comment]
Pypi registry updated: https://pypi.org/project/wellcomeml/

**Comment by nsorros** [comment]
Should we create a checklist and add to readme as things to do before releasing? We can even add it to the PR template and delete every time it is not a release

**Pull request merged**
